# Generated by Django 3.2.5 on 2021-08-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_name', models.CharField(max_length=100)),
                ('Date', models.DateField(blank=True, null=True)),
                ('Time', models.DurationField()),
                ('Location', models.CharField(max_length=100)),
                ('Image', models.ImageField(upload_to='image')),
            ],
        ),
    ]
